# Generated by Django 6.0.6 on 2026-06-30 12:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('provider', models.CharField(choices=[('Google', 'google'), ('Github', 'github')], max_length=20)),
                ('provider_user_id', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('provider', 'provider_user_id')},
            },
        ),
        migrations.CreateModel(
            name='TokenRefresh',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('jti', models.UUIDField(db_index=True, unique=True)),
                ('family_id', models.UUIDField(db_index=True)),
                ('parent_jti', models.UUIDField(blank=True, null=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('compromised', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['family_id'], name='auth_drf_to_family__9a7e77_idx'), models.Index(fields=['user_id'], name='auth_drf_to_user_id_cc6282_idx'), models.Index(fields=['expires_at'], name='auth_drf_to_expires_9f20e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('admin_id', models.IntegerField()),
                ('permissions', models.ManyToManyField(help_text='Role Based Permissions', to='auth.permission', verbose_name='role permissions')),
            ],
            options={
                'unique_together': {('name', 'admin_id')},
            },
        ),
    ]
